---
title: "Analysis of CMC III"

author: "Gabriel Hoffman"
date: "Run on `r Sys.Date()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{CMC II}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

<!--- 

# run analysis
cd /sc/orga/projects/CommonMind/hoffman/cmc_analysis
ml openssl pandoc
R

rmarkdown::render("src/compare_residuals.Rmd", output_dir='./', intermediates_dir='./')

# results:
https://hoffmg01.u.hpc.mssm.edu/commonmind/hoffman/cmc_analysis/
--->

Evaluate correlation in residuals from MSSM-Penn-Pitt - ACC and DLPFC from old and dream methods.

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(ggplot2)
library(gridExtra)
library(grid)
library(tidyverse)
library(variancePartition)
library(BiocParallel)
library(edgeR)
library(synapser)

synLogin()

register(SnowParam(12, "SOCK", progressbar=TRUE))

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE,
  cache.lazy = FALSE,
  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)

options(markdown.HTML.stylesheet = 'css/custom.css')
```



```{r load.residuals, echo=TRUE}
# Load residuals
res_std = read_tsv( synGet("syn21482408")$path )
res_dream = read_tsv( synGet("syn21548452")$path ) 


corRes = sapply( res_std$ensembl_gene_id, function(ensGene){
	x = res_std %>% filter( ensembl_gene_id == ensGene)
	y = res_dream %>% filter( ensembl_gene_id == ensGene)

	cor(as.numeric(x[-1]), as.numeric(y[-1]), use="pairwise.complete.obs")
})
```

# 
```{r plot.correlation, echo=TRUE}
hist(corRes, main="Correlation between residuals from old version and dream", xlab="Correlation")
```

```{r plot.ecdf}
df = data.frame(corr=corRes)
ggplot(df, aes(corr)) + stat_ecdf(geom = "step") + theme_bw(17) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + geom_vline(xintercept=0.95, color="red", linetype="dashed") + geom_vline(xintercept=0.90, color="darkgreen", linetype="dashed") + ggtitle("Empirical CDF") + ylab("Fraction greater than X") + xlab("Correlation")
```

`r format(sum(corRes>0.95) / length(corRes)*100, digits=3)`% of genes have a correlation > 0.95, and `r format(sum(corRes>0.90) / length(corRes)*100, digits=3)`% of genes have a correlation > 0.90.


```{r load.counts, echo=FALSE}
# load counts
counts_filtered_std = read_tsv( synGet("syn21482405")$path )
counts_filtered_dream = read_tsv( synGet("syn21548435")$path )

cov_std = read_tsv( synGet("syn21482397")$path )
cov_dream = read_tsv( synGet("syn21548433")$path )

# create formula
colType =  cov_dream %>% dplyr::summarise_all(class) %>%   tidyr::gather(variable, class)

form = sapply( 2:9, function(i){

  switch(colType$class[i], 
    "character" = paste0('(1|', colType$variable[i], ')'),
    "numeric" = colType$variable[i])
  })
form = as.formula(paste('~', paste(form, collapse=" + ")))


# geneExpr = as.matrix(counts_filtered_std[1:3,-1])
# geneExpr[is.na(geneExpr)] = 0
# rownames(geneExpr) = (counts_filtered_std %>% select(ensembl_gene_id))[1:3]

# fit_1 = dream( geneExpr, form, as.data.frame(cov_std))

```

# Compare ACC and DLPFC from same individual
```{r vp}

counts = read_tsv( synGet("syn21548434")$path )

M = as.matrix(counts[,-1])
rownames(M) = counts$ensembl_gene_id

dge = DGEList(M)
dge = calcNormFactors(dge)

vobj = voomWithDreamWeights( dge[1:10,], form, cov_dream)


vp = fitExtractVarPartModel( vobj, form, cov_dream)


```    




















