---
title: "RNA-seq from 4 cell populations"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---


<!---

cd /hpc/users/hoffmg01/work/cmc_analysis/src
# rm -rf molec_profiling_cache/
ml git pandoc
git pull
R

system("git pull")
rmarkdown::render("molec_profiling.Rmd", output_dir='./', intermediates_dir='./')


# http
# https://hoffmg01.u.hpc.mssm.edu/molec_profiling.html

--->


```{r load.packages, echo=FALSE, message=FALSE, results='hide', cache=FALSE}
suppressPackageStartupMessages({
library(variancePartition)
library(limma)
library(edgeR)
library(mvIC)
library(reshape2)
library(data.table)
library(BiocParallel)
library(knitr)
library(kableExtra)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(openxlsx)
})

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE,
  cache.lazy = FALSE,  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)

options(markdown.HTML.stylesheet = 'css/custom.css')
```

```{r read.data, messsage=TRUE}
file = "/sc/hydra/projects/CommonMind/roussp01a/MOLECULAR_PROFILING/rnaseq/step1-merged/featureCount/featureCount.gene.tsv.gz"
df_featureCounts_gene = fread( file )

geneInfo = df_featureCounts_gene[,1:6]
geneInfo$EnsId = gsub("^(.*)(\\.\\S+)$", "\\1", geneInfo$Geneid)

geneCounts = df_featureCounts_gene[,7:ncol(df_featureCounts_gene)]
geneCounts = as.data.frame(geneCounts)
rownames(geneCounts) = geneInfo$Geneid

# identify samples with improper names
idx = grep("Undetermined", colnames(geneCounts))
message("Dropping samples with improper names:\n",  paste(colnames(geneCounts)[idx], collapse="\n"))
geneCounts = geneCounts[,-idx]

idx = which(colSums(geneCounts) < 1e5)
message("Dropping samples with zero read counts:\n",  paste(colnames(geneCounts)[idx], collapse="\n"))
geneCounts = geneCounts[,-idx]

# remove genes with duplicated EnsId
exclude = duplicated(geneInfo$EnsId)
geneInfo = geneInfo[!exclude,]
geneCounts = geneCounts[!exclude,]
rownames(geneCounts) = gsub("^(.*)(\\.\\S+)$", "\\1", rownames(geneCounts))
```


```{r metadata}
# focused on this experiment
metadata1 = read.xlsx("/sc/hydra/projects/CommonMind/roussp01a/MOLECULAR_PROFILING/meta-files/MolecularProfiling_MSSM_120samples_05.24.17-4.xlsx")

# form Synapse
metadataCMC = fread("/sc/hydra/projects/CommonMind/roussp01a/MOLECULAR_PROFILING/meta-files/CMC_METADATA.csv")
```


```{r QC, fig.width=14, fig.height=36}
file = '/sc/hydra/projects/CommonMind/roussp01a/MOLECULAR_PROFILING/rnaseq/step1-merged/QCmetrics/qc_metrics.RDS'
qc_metrics.in = t(readRDS( file ))
colnames(qc_metrics.in) = qc_metrics.in[1,]
qc_metrics.in = as.data.frame(qc_metrics.in[-c(1:2),], stringsAsFactors=FALSE)
qc_metrics = apply(qc_metrics.in, 2, as.numeric)
rownames(qc_metrics) = gsub('-', '.', rownames(qc_metrics.in))

# extract information from sample names
info = data.frame( Name = colnames(geneCounts), stringsAsFactors=FALSE)
rownames(info) = info$Name
info$DissectionID = sapply(strsplit( info$Name, '\\.'), function(x) x[1])
info$CellType = sapply(strsplit( info$Name, '\\.'), function(x) x[2])
info$Assay = sapply(strsplit( info$Name, '\\.'), function(x) x[3])

# set color codes cor each cell type
colorCodes = c(
  GABA = '#66A61E',
  GLU = '#E6AB02',
  Olig = '#E7298A',
  MgAs = '#7570B3')

# set factor levels to be the same as the order of the colors
# this makes plotting easier
info$CellType = factor(info$CellType,names(colorCodes))

# add information about each sample
info = merge(info, metadata1, by.x="DissectionID", by.y='Dissection.ID')
info = merge(info, qc_metrics, by.x="Name", by.y='row.names')


# info = merge(info, metadataCMC, by.x='Individual.ID', by.y="Individual ID")
#  info[1:4, 1:20]

# set order to be the same as geneCounts
info = info[match(colnames(geneCounts), info$Name),]


# exclude columns with no variance
index = apply(qc_metrics, 2, function(x) var(x, na.rm=TRUE)) > 0
include = which(index==TRUE)
include = include[! names(include) %in% "PF_BASES"]

df = reshape2::melt(info[,c('DissectionID', 'CellType', colnames(qc_metrics)[include])], id.vars=c('DissectionID', 'CellType'))

ggplot(df, aes( x=CellType, y=value, fill=CellType)) + geom_boxplot() + facet_wrap(~variable, scales="free_y", ncol=6) + theme_bw(8) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5), legend.position="none") + scale_fill_manual("Cell Type", values=colorCodes) 
```



```{r exit, cache=FALSE}
knitr::knit_exit()
```


### Study Summary
```{r}
kable(table(info$Dx, info$CellType))  %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

```{r}
kable(table(info$Individual.ID))  %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

```{r preprocess}
isexpr = rowSums(cpm(geneCounts)>1) >= 0.1*ncol(geneCounts)
table(isexpr)

dge = DGEList( geneCounts[isexpr,] )
dge = calcNormFactors(dge)
```


### PCA
```{r PCA, fig.width=9}

geneExpr = cpm(dge, log=TRUE)

dcmp = prcomp( t(geneExpr), scale=TRUE)

df_pca = data.frame(dcmp$x)

df_pca = merge(df_pca, info, by.x="row.names", by.y="Name")

varFrac = dcmp$sdev^2 / sum(dcmp$sdev^2)

xlab = paste0('PC1 (', format(varFrac[1]*100, digits=3), '%)')
ylab = paste0('PC2 (', format(varFrac[2]*100, digits=3), '%)')
ggplot(df_pca, aes(PC1, PC2, color=CellType)) + geom_point() + theme_bw(15) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5), legend.position='none') + scale_color_manual("Cell Type", values=colorCodes) + xlab(xlab) + ylab(ylab)

xlab = paste0('PC2 (', format(varFrac[2]*100, digits=3), '%)')
ylab = paste0('PC3 (', format(varFrac[3]*100, digits=3), '%)')
ggplot(df_pca, aes(PC2, PC3, color=CellType)) + geom_point() + theme_bw(15) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + scale_color_manual("Cell Type", values=colorCodes) + xlab(xlab) + ylab(ylab)
```      



### Differential expression
```{r dream}
form = ~ (1|CellType) + (1|Individual.ID) + (1|Gender)
vobj = voomWithDreamWeights(dge, form, info, plot=TRUE, save.plot=TRUE, BPPARAM=SnowParam(6, progressbar=TRUE))

fitBasic = dream( vobj, ~ CellType + (1|Individual.ID) + (1|Gender), info, BPPARAM=SnowParam(6, progressbar=TRUE))

fitDisease = dream( vobj, ~ CellType*Dx + (1|Individual.ID) + (1|Gender), info, BPPARAM=SnowParam(6, progressbar=TRUE))
```


### variancePartition
```{r vp}
form = ~ (1|CellType) + (1|Dx) + (1|CellType:Dx) + (1|Individual.ID) + (1|Gender)
vp = fitExtractVarPartModel( geneExpr, form, info, BPPARAM=SnowParam(6, progressbar=TRUE))

plotVarPart( sortCols(vp) )
```





```{r plot.DE.results}

# lapply( levels(info$CellType), function(CT){


#   ensID = rownames(topTable( fit, coef=paste0('CellType', CT), number=10))


#   df = merge( data.frame(Expression = geneExpr[ensID[1],]), info, by="row.names")

#   ggplot(df, aes(CellType, Expression, color=CellType)) + geom_point() + theme_bw(15) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5) + scale_color_manual("Cell Type", values=colorCodes) + ggtitle( ensID )




#   } )



```


# Disease by cell type interaction
```{r }

```


















